// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEIDZVoBEUC8-YHdHunCqTdqvPHO5zido',
    appId: '1:1054907445264:web:c47f91b1d9de758e18da95',
    messagingSenderId: '1054907445264',
    projectId: 'olimpiacos-21c4b',
    authDomain: 'olimpiacos-21c4b.firebaseapp.com',
    storageBucket: 'olimpiacos-21c4b.appspot.com',
    measurementId: 'G-7KE3Q6PLP9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_yi1IwGwy0yHnihFyGkQETt0SI3EQ8EA',
    appId: '1:1054907445264:android:c8469c3ad04616ec18da95',
    messagingSenderId: '1054907445264',
    projectId: 'olimpiacos-21c4b',
    storageBucket: 'olimpiacos-21c4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiqfAGC6Wzno-iVTg0cDUsDGxtdtoNq7c',
    appId: '1:1054907445264:ios:9a29649785f2fb9418da95',
    messagingSenderId: '1054907445264',
    projectId: 'olimpiacos-21c4b',
    storageBucket: 'olimpiacos-21c4b.appspot.com',
    iosBundleId: 'com.example.olimpicos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiqfAGC6Wzno-iVTg0cDUsDGxtdtoNq7c',
    appId: '1:1054907445264:ios:9a29649785f2fb9418da95',
    messagingSenderId: '1054907445264',
    projectId: 'olimpiacos-21c4b',
    storageBucket: 'olimpiacos-21c4b.appspot.com',
    iosBundleId: 'com.example.olimpicos',
  );
}
